"""key_and_location

Revision ID: 0c64bfa92c16
Revises: e55a03f09cc8
Create Date: 2024-12-05 15:54:52.261605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c64bfa92c16'
down_revision = 'e55a03f09cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', sa.String(length=64), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_actors_key'), ['key'])
        batch_op.drop_column('uuid')

    with op.batch_alter_table('directors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', sa.String(length=64), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_directors_key'), ['key'])
        batch_op.drop_column('uuid')

    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_genres_key'), ['key'])

    with op.batch_alter_table('movie_translations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=128), nullable=False))

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_movies_key'), ['key'])
        batch_op.drop_column('uuid')

    with op.batch_alter_table('subgenres', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_subgenres_key'), ['key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subgenres', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_subgenres_key'), type_='unique')

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_movies_key'), type_='unique')
        batch_op.drop_column('key')

    with op.batch_alter_table('movie_translations', schema=None) as batch_op:
        batch_op.drop_column('location')

    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_genres_key'), type_='unique')

    with op.batch_alter_table('directors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_directors_key'), type_='unique')
        batch_op.drop_column('key')

    with op.batch_alter_table('actors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_actors_key'), type_='unique')
        batch_op.drop_column('key')

    # ### end Alembic commands ###
