"""user_auth

Revision ID: 29ee4acf72a8
Revises: 7744fd0fab85
Create Date: 2025-04-02 17:44:24.230409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ee4acf72a8'
down_revision = '7744fd0fab85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=512), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('email')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
