"""similar movies algorithm

Revision ID: 2e956a042cb6
Revises: a077c4cd6fe0
Create Date: 2026-06-30 15:45:32.875981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e956a042cb6'
down_revision = 'a077c4cd6fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_similarities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_a_id', sa.Integer(), nullable=False),
    sa.Column('movie_b_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('movie_a_id < movie_b_id', name=op.f('ck_movie_similarities_ck_movie_similarity_ordered_pair')),
    sa.ForeignKeyConstraint(['movie_a_id'], ['movies.id'], name=op.f('fk_movie_similarities_movie_a_id_movies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_b_id'], ['movies.id'], name=op.f('fk_movie_similarities_movie_b_id_movies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movie_similarities')),
    sa.UniqueConstraint('movie_a_id', 'movie_b_id', name='uq_movie_similarity_pair')
    )
    with op.batch_alter_table('movie_similarities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movie_similarities_movie_a_id'), ['movie_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movie_similarities_movie_b_id'), ['movie_b_id'], unique=False)
        batch_op.create_index('ix_movie_similarities_score', ['score'], unique=False)

    with op.batch_alter_table('action_times', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_count', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_count', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_count', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('movie_genres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('movie_keywords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('movie_specifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('movie_subgenres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('specifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_count', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('subgenres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_count', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subgenres', schema=None) as batch_op:
        batch_op.drop_column('movie_count')

    with op.batch_alter_table('specifications', schema=None) as batch_op:
        batch_op.drop_column('movie_count')

    with op.batch_alter_table('movie_subgenres', schema=None) as batch_op:
        batch_op.drop_column('rank')

    with op.batch_alter_table('movie_specifications', schema=None) as batch_op:
        batch_op.drop_column('rank')

    with op.batch_alter_table('movie_keywords', schema=None) as batch_op:
        batch_op.drop_column('rank')

    with op.batch_alter_table('movie_genres', schema=None) as batch_op:
        batch_op.drop_column('rank')

    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.drop_column('movie_count')

    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.drop_column('movie_count')

    with op.batch_alter_table('action_times', schema=None) as batch_op:
        batch_op.drop_column('movie_count')

    with op.batch_alter_table('movie_similarities', schema=None) as batch_op:
        batch_op.drop_index('ix_movie_similarities_score')
        batch_op.drop_index(batch_op.f('ix_movie_similarities_movie_b_id'))
        batch_op.drop_index(batch_op.f('ix_movie_similarities_movie_a_id'))

    op.drop_table('movie_similarities')
    # ### end Alembic commands ###
