"""shared_universe

Revision ID: 30252946b43d
Revises: ae48ba38b60b
Create Date: 2025-03-24 12:59:39.062070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30252946b43d'
down_revision = 'ae48ba38b60b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_universes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shared_universes')),
    sa.UniqueConstraint('key', name=op.f('uq_shared_universes_key'))
    )
    op.create_table('shared_universe_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shared_universe_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['shared_universe_id'], ['shared_universes.id'], name=op.f('fk_shared_universe_translations_shared_universe_id_shared_universes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shared_universe_translations'))
    )
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_universe_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shared_universe_order', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_movies_shared_universe_id_shared_universes'), 'shared_universes', ['shared_universe_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_movies_shared_universe_id_shared_universes'), type_='foreignkey')
        batch_op.drop_column('shared_universe_order')
        batch_op.drop_column('shared_universe_id')

    op.drop_table('shared_universe_translations')
    op.drop_table('shared_universes')
    # ### end Alembic commands ###
