"""21_order_movie_actor_character

Revision ID: 33e9f2a78496
Revises: 642577b2edbc
Create Date: 2025-04-21 09:25:48.856665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e9f2a78496'
down_revision = '642577b2edbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_actor_character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_actor_character', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
