"""23_visual_profile

Revision ID: 376c9a1295d5
Revises: 8d8759a1efb2
Create Date: 2025-05-28 08:44:40.351472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376c9a1295d5'
down_revision = '8d8759a1efb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('title_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_title_categories'))
    )
    with op.batch_alter_table('title_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_title_categories_key'), ['key'], unique=True)

    op.create_table('title_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_title_criteria'))
    )
    with op.batch_alter_table('title_criteria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_title_criteria_key'), ['key'], unique=True)

    op.create_table('category_criteria',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['title_categories.id'], name=op.f('fk_category_criteria_category_id_title_categories')),
    sa.ForeignKeyConstraint(['criterion_id'], ['title_criteria.id'], name=op.f('fk_category_criteria_criterion_id_title_criteria')),
    sa.PrimaryKeyConstraint('category_id', 'criterion_id', name=op.f('pk_category_criteria'))
    )
    op.create_table('title_category_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_category_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['title_category_id'], ['title_categories.id'], name=op.f('fk_title_category_translations_title_category_id_title_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_title_category_translations'))
    )
    op.create_table('title_criterion_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_criterion_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['title_criterion_id'], ['title_criteria.id'], name=op.f('fk_title_criterion_translations_title_criterion_id_title_criteria')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_title_criterion_translations'))
    )
    op.create_table('title_visual_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['title_categories.id'], name=op.f('fk_title_visual_profiles_category_id_title_categories')),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_title_visual_profiles_movie_id_movies')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_title_visual_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_title_visual_profiles'))
    )
    op.create_table('title_criterion_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_visual_profile_id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['title_criteria.id'], name=op.f('fk_title_criterion_ratings_criterion_id_title_criteria')),
    sa.ForeignKeyConstraint(['title_visual_profile_id'], ['title_visual_profiles.id'], name=op.f('fk_title_criterion_ratings_title_visual_profile_id_title_visual_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_title_criterion_ratings'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('title_criterion_ratings')
    op.drop_table('title_visual_profiles')
    op.drop_table('title_criterion_translations')
    op.drop_table('title_category_translations')
    op.drop_table('category_criteria')
    with op.batch_alter_table('title_criteria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_title_criteria_key'))

    op.drop_table('title_criteria')
    with op.batch_alter_table('title_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_title_categories_key'))

    op.drop_table('title_categories')
    # ### end Alembic commands ###
