"""25_knowledge_base_category_technology_q&a

Revision ID: 38523f8a1cff
Revises: b098f992f9ff
Create Date: 2025-09-16 06:32:18.438350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38523f8a1cff'
down_revision = 'b098f992f9ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_base_categories')),
    sa.UniqueConstraint('key', name=op.f('uq_knowledge_base_categories_key'))
    )
    op.create_table('knowledge_base_technologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['knowledge_base_categories.id'], name=op.f('fk_knowledge_base_technologies_category_id_knowledge_base_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_base_technologies')),
    sa.UniqueConstraint('key', name=op.f('uq_knowledge_base_technologies_key'))
    )
    op.create_table('knowledge_base_question_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('short_answer', sa.String(length=512), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['technology_id'], ['knowledge_base_technologies.id'], name=op.f('fk_knowledge_base_question_answers_technology_id_knowledge_base_technologies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_base_question_answers'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_base_question_answers')
    op.drop_table('knowledge_base_technologies')
    op.drop_table('knowledge_base_categories')
    # ### end Alembic commands ###
