"""average_by_criteria

Revision ID: 4882555c5d53
Revises: 29ee4acf72a8
Create Date: 2025-04-04 09:15:00.467364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4882555c5d53'
down_revision = '29ee4acf72a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_by_criteria', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('average_by_criteria')

    # ### end Alembic commands ###
