"""movie_character_actor

Revision ID: 4c482dab720d
Revises: 81409746c144
Create Date: 2024-12-16 13:22:40.592149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c482dab720d'
down_revision = '81409746c144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_characters')),
    sa.UniqueConstraint('key', name=op.f('uq_characters_key'))
    )
    op.create_table('actor_characters',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], name=op.f('fk_actor_characters_actor_id_actors')),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_actor_characters_character_id_characters')),
    sa.PrimaryKeyConstraint('character_id', 'actor_id', name=op.f('pk_actor_characters'))
    )
    op.create_table('character_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_translations_character_id_characters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_character_translations'))
    )
    op.create_table('movie_characters',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_movie_characters_character_id_characters')),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_movie_characters_movie_id_movies')),
    sa.PrimaryKeyConstraint('character_id', 'movie_id', name=op.f('pk_movie_characters'))
    )
    with op.batch_alter_table('actor_translations', schema=None) as batch_op:
        batch_op.drop_column('character_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actor_translations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    op.drop_table('movie_characters')
    op.drop_table('character_translations')
    op.drop_table('actor_characters')
    op.drop_table('characters')
    # ### end Alembic commands ###
