"""movie_poster

Revision ID: 514ab1cb9823
Revises: f49bbe78ac99
Create Date: 2024-12-02 12:38:09.760600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514ab1cb9823'
down_revision = 'f49bbe78ac99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('poster')

    # ### end Alembic commands ###
