"""movie_actor_character

Revision ID: 7744fd0fab85
Revises: 30252946b43d
Create Date: 2025-03-27 14:19:11.945051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7744fd0fab85'
down_revision = '30252946b43d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_actor_character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], name=op.f('fk_movie_actor_character_actor_id_actors')),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_movie_actor_character_character_id_characters')),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_movie_actor_character_movie_id_movies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movie_actor_character')),
    sa.UniqueConstraint('movie_id', 'actor_id', 'character_id', name='uq_movie_actor_character')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_actor_character')
    # ### end Alembic commands ###
