"""action_time_order

Revision ID: 7e65849c9863
Revises: 2e956a042cb6
Create Date: 2026-07-03 08:08:58.104139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e65849c9863'
down_revision = '2e956a042cb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_times', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_times', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
