"""rating_user

Revision ID: 81409746c144
Revises: 0c64bfa92c16
Create Date: 2024-12-11 10:57:09.914272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81409746c144'
down_revision = '0c64bfa92c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=512), server_default='', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('comment', sa.String(length=512), nullable=False),
    sa.Column('acting', sa.Float(), nullable=False),
    sa.Column('plot_storyline', sa.Float(), nullable=False),
    sa.Column('music', sa.Float(), nullable=False),
    sa.Column('re_watchability', sa.Float(), nullable=False),
    sa.Column('emotional_impact', sa.Float(), nullable=False),
    sa.Column('dialogue', sa.Float(), nullable=False),
    sa.Column('production_design', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('visual_effects', sa.Float(), nullable=True),
    sa.Column('scare_factor', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_ratings_movie_id_movies')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ratings_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ratings'))
    )
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_rating', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('ratings_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('rating_criterion', sa.String(length=36), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('rating_criterion')
        batch_op.drop_column('ratings_count')
        batch_op.drop_column('average_rating')

    op.drop_table('ratings')
    op.drop_table('users')
    # ### end Alembic commands ###
