"""movie_specification

Revision ID: 8ec5f4b7fffa
Revises: b582395a525c
Create Date: 2024-12-17 14:32:34.089764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec5f4b7fffa'
down_revision = 'b582395a525c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_specifications'))
    )
    with op.batch_alter_table('specifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_specifications_key'), ['key'], unique=True)

    op.create_table('movie_specifications',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('specification_id', sa.Integer(), nullable=False),
    sa.Column('percentage_match', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_movie_specifications_movie_id_movies')),
    sa.ForeignKeyConstraint(['specification_id'], ['specifications.id'], name=op.f('fk_movie_specifications_specification_id_specifications')),
    sa.PrimaryKeyConstraint('movie_id', 'specification_id', name=op.f('pk_movie_specifications'))
    )
    op.create_table('specification_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specification_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['specification_id'], ['specifications.id'], name=op.f('fk_specification_translations_specification_id_specifications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_specification_translations'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specification_translations')
    op.drop_table('movie_specifications')
    with op.batch_alter_table('specifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_specifications_key'))

    op.drop_table('specifications')
    # ### end Alembic commands ###
