"""update_rating_criteria

Revision ID: 98e713417c3c
Revises: db5e01ecd652
Create Date: 2025-01-20 15:58:06.042973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e713417c3c'
down_revision = 'db5e01ecd652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('script_dialogue', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('enjoyment', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('humor', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('animation_cartoon', sa.Float(), nullable=True))
        batch_op.drop_column('re_watchability')
        batch_op.drop_column('dialogue')
        batch_op.drop_column('emotional_impact')
        batch_op.drop_column('duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('emotional_impact', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('dialogue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('re_watchability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('animation_cartoon')
        batch_op.drop_column('humor')
        batch_op.drop_column('enjoyment')
        batch_op.drop_column('script_dialogue')

    # ### end Alembic commands ###
