"""director_table

Revision ID: 99eb60894f40
Revises: 514ab1cb9823
Create Date: 2024-12-03 09:45:47.384661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99eb60894f40'
down_revision = '514ab1cb9823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('born', sa.DateTime(), nullable=False),
    sa.Column('died', sa.DateTime(), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_directors'))
    )
    op.create_table('director_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('director_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('born_in', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['director_id'], ['directors.id'], name=op.f('fk_director_translations_director_id_directors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_director_translations'))
    )
    op.create_table('movie_directors',
    sa.Column('director_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['director_id'], ['directors.id'], name=op.f('fk_movie_directors_director_id_directors')),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_movie_directors_movie_id_movies')),
    sa.PrimaryKeyConstraint('director_id', 'movie_id', name=op.f('pk_movie_directors'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_directors')
    op.drop_table('director_translations')
    op.drop_table('directors')
    # ### end Alembic commands ###
