"""27_update_question_answer_fields

Revision ID: a077c4cd6fe0
Revises: 38523f8a1cff
Create Date: 2025-09-25 18:41:07.941765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a077c4cd6fe0'
down_revision = '38523f8a1cff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_base_question_answers', schema=None) as batch_op:
        batch_op.alter_column('short_answer',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
        batch_op.alter_column('answer',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_base_question_answers', schema=None) as batch_op:
        batch_op.alter_column('answer',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('short_answer',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)

    # ### end Alembic commands ###
