"""related_movies

Revision ID: ae48ba38b60b
Revises: 98e713417c3c
Create Date: 2025-03-24 08:16:18.578120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae48ba38b60b'
down_revision = '98e713417c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_time_translations', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('genre_translations', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('keyword_translations', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collection_order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('relation_type', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('collection_base_movie_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_movies_collection_base_movie_id_movies'), 'movies', ['collection_base_movie_id'], ['id'])

    with op.batch_alter_table('specification_translations', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('subgenre_translations', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subgenre_translations', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('specification_translations', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_movies_collection_base_movie_id_movies'), type_='foreignkey')
        batch_op.drop_column('collection_base_movie_id')
        batch_op.drop_column('relation_type')
        batch_op.drop_column('collection_order')

    with op.batch_alter_table('keyword_translations', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('genre_translations', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('action_time_translations', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
