"""24_update_filter_tables_with_uuid

Revision ID: b098f992f9ff
Revises: 73ff37ed82dc
Create Date: 2025-06-04 08:25:49.461357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b098f992f9ff'
down_revision = '73ff37ed82dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_times', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=True))

    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=True))

    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=True))

    with op.batch_alter_table('specifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=True))

    with op.batch_alter_table('subgenres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subgenres', schema=None) as batch_op:
        batch_op.drop_column('uuid')

    with op.batch_alter_table('specifications', schema=None) as batch_op:
        batch_op.drop_column('uuid')

    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.drop_column('uuid')

    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.drop_column('uuid')

    with op.batch_alter_table('action_times', schema=None) as batch_op:
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
