"""movie_action_time

Revision ID: db5e01ecd652
Revises: fbbef0e0f42e
Create Date: 2024-12-17 18:27:43.939795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db5e01ecd652'
down_revision = 'fbbef0e0f42e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_times'))
    )
    with op.batch_alter_table('action_times', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_times_key'), ['key'], unique=True)

    op.create_table('action_time_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_time_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['action_time_id'], ['action_times.id'], name=op.f('fk_action_time_translations_action_time_id_action_times')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_time_translations'))
    )
    op.create_table('movie_action_times',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('action_time_id', sa.Integer(), nullable=False),
    sa.Column('percentage_match', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['action_time_id'], ['action_times.id'], name=op.f('fk_movie_action_times_action_time_id_action_times')),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_movie_action_times_movie_id_movies')),
    sa.PrimaryKeyConstraint('movie_id', 'action_time_id', name=op.f('pk_movie_action_times'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_action_times')
    op.drop_table('action_time_translations')
    with op.batch_alter_table('action_times', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_times_key'))

    op.drop_table('action_times')
    # ### end Alembic commands ###
