"""genres

Revision ID: e55a03f09cc8
Revises: 99eb60894f40
Create Date: 2024-12-05 12:43:09.952742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e55a03f09cc8'
down_revision = '99eb60894f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genres'))
    )
    op.create_table('genre_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_genre_translations_genre_id_genres')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genre_translations'))
    )
    op.create_table('movie_genres',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_movie_genres_genre_id_genres')),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_movie_genres_movie_id_movies')),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id', name=op.f('pk_movie_genres'))
    )
    op.create_table('subgenres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=36), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_subgenres_genre_id_genres')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subgenres'))
    )
    op.create_table('genre_subgenres',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('subgenre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_genre_subgenres_genre_id_genres')),
    sa.ForeignKeyConstraint(['subgenre_id'], ['subgenres.id'], name=op.f('fk_genre_subgenres_subgenre_id_subgenres')),
    sa.PrimaryKeyConstraint('genre_id', 'subgenre_id', name=op.f('pk_genre_subgenres'))
    )
    op.create_table('movie_subgenres',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('subgenre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_movie_subgenres_movie_id_movies')),
    sa.ForeignKeyConstraint(['subgenre_id'], ['subgenres.id'], name=op.f('fk_movie_subgenres_subgenre_id_subgenres')),
    sa.PrimaryKeyConstraint('movie_id', 'subgenre_id', name=op.f('pk_movie_subgenres'))
    )
    op.create_table('subgenre_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subgenre_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['subgenre_id'], ['subgenres.id'], name=op.f('fk_subgenre_translations_subgenre_id_subgenres')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subgenre_translations'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subgenre_translations')
    op.drop_table('movie_subgenres')
    op.drop_table('genre_subgenres')
    op.drop_table('subgenres')
    op.drop_table('movie_genres')
    op.drop_table('genre_translations')
    op.drop_table('genres')
    # ### end Alembic commands ###
