"""actor_table

Revision ID: f49bbe78ac99
Revises: 35318f8fe089
Create Date: 2024-12-02 09:39:50.439101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f49bbe78ac99'
down_revision = '35318f8fe089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('born', sa.DateTime(), nullable=False),
    sa.Column('died', sa.DateTime(), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actors'))
    )
    op.create_table('actor_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('born_in', sa.String(length=255), nullable=True),
    sa.Column('character_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], name=op.f('fk_actor_translations_actor_id_actors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actor_translations'))
    )
    op.create_table('movie_actors',
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], name=op.f('fk_movie_actors_actor_id_actors')),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_movie_actors_movie_id_movies')),
    sa.PrimaryKeyConstraint('actor_id', 'movie_id', name=op.f('pk_movie_actors'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_actors')
    op.drop_table('actor_translations')
    op.drop_table('actors')
    # ### end Alembic commands ###
