"""movie_keyword

Revision ID: fbbef0e0f42e
Revises: 8ec5f4b7fffa
Create Date: 2024-12-17 16:52:08.598819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbbef0e0f42e'
down_revision = '8ec5f4b7fffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keywords'))
    )
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_keywords_key'), ['key'], unique=True)

    op.create_table('keyword_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], name=op.f('fk_keyword_translations_keyword_id_keywords')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_translations'))
    )
    op.create_table('movie_keywords',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('percentage_match', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], name=op.f('fk_movie_keywords_keyword_id_keywords')),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_movie_keywords_movie_id_movies')),
    sa.PrimaryKeyConstraint('movie_id', 'keyword_id', name=op.f('pk_movie_keywords'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_keywords')
    op.drop_table('keyword_translations')
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keywords_key'))

    op.drop_table('keywords')
    # ### end Alembic commands ###
